name: Deploy to website-staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source (staging branch)
      uses: actions/checkout@v3

    - name: Deploy to website-staging
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.STAGING_TOKEN }}
        external_repository: contestra/website-staging
        publish_branch: main
        publish_dir: ./
